name: SoT
channels:
  - defaults
dependencies:
  - python=3.12        # or whichever 3.x you prefer
  - pip
  - pip:
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - grpcio==1.68.0
    - grpcio-tools==1.68.0
    - idna==3.10
    - protobuf==5.29.0
    - requests==2.32.3
    - urllib3==2.3.0
    - scripts-of-tribute
    - matplotlib
    - seaborn
